name: CI/CD Pipeline # Initial pipeline, still need the vm for test

on:
  push:
    #branches: [ "main" ]
    branches: ['*'] # The workflow will be execute on all branches
  pull_request:
    branches: ['*']
    #branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - run: cd API/
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  #deploy:
    #runs-on: ubuntu-latest
    #needs: build
    #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #steps:
    #- name: SSH Remote Commands
        # You may pin to the exact commit or the version.
        # uses: appleboy/ssh-action@f9010ff7f1bbd7db1a0b4bab661437550cea20c0
      #uses: appleboy/ssh-action@v0.1.5
      #with:
          # ssh host
          #host: 8.8.8.8
          # ssh port
          #port: 33333
          # ssh key passphrase
          # passphrase: # optional
          # ssh username
          #username: ${{ secrets.USERNAME }}
          # ssh password
          #password: ${{ secrets.PASSWORD }}
          # run scripts
          # script: |
            #cd /home/toure
            #git fetch && git pull
            #systemctl restart api 
          # stop script after first failure
          #script_stop: true